name: detekt

on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "1.1" ]
  pull_request:
    branches: [ "1.1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_detekt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 20
      - name: Cache Gradlew packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      - name: Run detekt
        run: ./gradlew detekt
