name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  path_to_release: app/build/outputs/apk/release

  path_to_debug: app/build/outputs/apk/debug
  # The name of the Play Store
  playstore_name: Nine mens morris

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "1.1" ]
  pull_request:
    branches: [ "1.1" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      # Install apk signer and base64
      - name: Install apk-signer
        run: |
          sudo apt-get update &
          sudo apt-get install apksigner

      # Run Build Project
      - name: Build gradle project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK) - app module
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) - app module
        run: ./gradlew assemble

      # Decode keystore
      - name: Decode keystore.txt
        run: |
          echo ${{ secrets.KEYSTORE_TXT }} > ~/keystore.txt
          base64 -d ~/keystore.txt > ~/keystore.jks

      # Sign apk
      - name: Sign apk
        run: |
          apksigner sign --ks ~/keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --out ${{ env.path_to_release }}/app-release-signed.apk  ${{ env.path_to_release }}/app-release.apk
          apksigner sign --ks ~/keystore.jks --ks-pass pass:${{ secrets.KEYSTORE_PASSWORD }} --out ${{ env.path_to_debug }}/app-debug-signed.apk  ${{ env.path_to_debug }}/app-debug.apk

      # Upload Artifact Build
      # Noted For Output [main_project_module]/build/outputs/apk/debug/
      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK debug
          path: ${{ env.path_to_debug }}/app-debug-signed.apk

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release
          path: ${{ env.path_to_release }}/app-release-signed.apk
